%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Generate graph Freq Response - 09/07/2019         %
% Arkadi Rafalovich - % Arkadiraf@gmail.com         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clc
clear

%% Setup description
%{
Mic Speaker distance 0.5m
Supply voltage to Speaker 12V
Mic gain 2, mic thresh 50%
HPF on.
Signal generated by a Chirp box

Data:
analog_channel_2  - Mic 1
analog_channel_3  - Mic 2
%}

%% open data
load MicDelay_1000vs1.mat
MicDelay1.Mic1 = analog_channel_2;
MicDelay1.Mic2 = analog_channel_3;
MicDelay1.time_vector = ((1:1:size(analog_channel_2,1))/analog_sample_rate_hz)';
load MicDelay_1000vs3000.mat
MicDelay2.Mic1 = analog_channel_2;
MicDelay2.Mic2 = analog_channel_3;
MicDelay2.time_vector = ((1:1:size(analog_channel_2,1))/analog_sample_rate_hz)';

%% Select data for plot
windowsSize = 0.008;
figure(1); % time response
subplot(2,1,1)
start = 0.098;
plot(MicDelay1.time_vector,MicDelay1.Mic1)
hold on
plot(MicDelay1.time_vector,MicDelay1.Mic2)
hold off
title({'{\bf\fontsize{14} Smart Microphone Delay}';''; '(a) Mic 1 delayed 1000 samples, Mic 2 delayed 1 samples'})
xlim([start start+windowsSize]);
ylim([0 3.3]);
xlabel('Time (sec)');
ylabel('Amplitude (v)');
legend('Mic 1','Mic 2')
grid on


subplot(2,1,2)
start = 0.50823;
plot(MicDelay2.time_vector,MicDelay2.Mic1)
hold on
plot(MicDelay2.time_vector,MicDelay2.Mic2)
hold off
title('(b) Mic 1 delayed 1000 samples, Mic 2 delayed 3000 samples');
xlim([start start+windowsSize]);
ylim([0 3.3]);
xlabel('Time (sec)');
ylabel('Amplitude (v)');
legend('Mic 1','Mic 2')
grid on
